config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/ijndex'
  root "home#ijndex"
  get "home/about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :friends
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
 class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit,:update,:destroy]
  # GET /friends or /friends.json

  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build()
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user  
    @friends = current_user.friends.find_by(id: params[:id])
    # if @friend.nil? == true then redirec and notice
    redirect_to friends_path , notice: "You are NOT Correct User!" if @friends.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :comment,:user_id)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def ijndex
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>
  <div class="field" style="display: none;">
    <%= form.label :user_id,id: :friend_user_id,type: :hidden %>
    <%= form.number_field :user_id ,id: :friend_user_id,type: :hidden,value:current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend ,class:"cool-a-tag-1"%> |
<%= link_to 'Back', friends_path ,class:"cool-a-tag-1" %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Comment</th>
      <th>user_id</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
          <!-- <h1><%= friend.user.email %> == <%=current_user.email  %> </h1> -->
        
        <tr>
          <td><%= friend.name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.comment %></td>
          <td><%= friend.user_id %></td>

          <td><%= link_to 'Show', friend ,class:"cool-a-tag-1"%></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) ,class:"cool-a-tag-2" %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' },class:"cool-a-tag-1" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path ,class:"cool-a-tag-2"%>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend ,class:"cool-a-tag-1"%>

<%= link_to 'Back', friends_path ,class:"cool-a-tag-1"%>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @friend.comment %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) ,class:"cool-a-tag-2"%> |
<%= link_to 'Back', friends_path ,class:"cool-a-tag-1"%>

app/views/home/_header.html.erb
<header>
	<nav class="banner" >
		<div class="to-inline-block">
			<%= link_to "ZainFriends", root_path , class:"logo-tag"%>

		</div>
		
		<ul class="ul-li-aliner to-inline-block a-tage-cleaner">
			<li><%= link_to "home",root_path ,class:"cool-a-tag-3"%></li>
			<li><%= link_to "All Comment", friends_path, class:"cool-a-tag-3"%></li>
			<% if user_signed_in?%>
				<li><%=link_to "Add Comment",new_friend_path, class:"cool-a-tag-3"%></li>
				<li><%= link_to "LogOut",destroy_user_session_path ,method: :delete ,class:"cool-a-tag-3"%></li>
				<li><%= link_to "EditProfile",edit_user_registration_path ,class:"cool-a-tag-3"%></li>			
			<%else%>
				<li><%= link_to "LogIn",new_user_session_path ,class:"cool-a-tag-3"%></li>
				<li><%= link_to "SignUp",new_user_registration_path ,class:"cool-a-tag-3"%></li>			
			<%end%>
			

		</ul>
	</nav>
</header>

app/views/home/about.html.erb
<h1>shack hands with rails...</h1>

app/views/home/ijndex.html.erb
<h1>meeting with Ruby...</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- no need for _ or .html.erb because render dose it.-->
    <%= render  'home/header'%>
    <div class = "card-3d text-center">
      <%= yield %>
    </div>

  </body>
</html>